export const ROUTES = {
  NOTFOUND: '*',
  HOME: '/',
  ABOUT: '/about',
  ITEMS: '/items',
  EDIT: '/edit',
  ADDITEM: '/additem',
  CATALOG: '/catalog',
  PROFILE: '/profile',
  USER: '/user',
  MESSENGER: '/messenger',
  MESSEGES: '/messenger/messeges',
  FAVOURITES: '/profile/favourites',
  SETTINGS: '/profile/settings',
  LOGIN: '/login',
  REGISTER: '/register',
}
